// <auto-generated />
namespace FingerPrint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202205200700165_AddStaffchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202205200700165_AddStaffchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202205200703562_202205200700165_AddStaffchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
